services:
  portfolio:
    build: .
    container_name: portfolio
    ports:
      - "8050:8000"
    environment:
      PROFILE_NAME: "portfolio-name"
      CONTENT_DIR: "/docs"
      DEFAULT_MD: "portfolio.md"
    volumes:
      - /mnt/NVME1/Docker/portfolio:/docs:ro
    restart: unless-stopped
